// <auto-generated />
using System;
using CampusConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211074236_allEntries")]
    partial class allEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("CampusConnect.Models.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RSVPCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = "e1",
                            Category = "Fair",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meet all clubs on campus!",
                            Location = "Main Gym",
                            RSVPCount = 0,
                            Title = "Campus Club Fair"
                        },
                        new
                        {
                            EventId = "e2",
                            Category = "Workshop",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Improve your math skills",
                            Location = "Room 101",
                            RSVPCount = 0,
                            Title = "Math Workshop"
                        },
                        new
                        {
                            EventId = "e3",
                            Category = "Fair",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Showcase science projects",
                            Location = "Science Hall",
                            RSVPCount = 0,
                            Title = "Science Fair"
                        },
                        new
                        {
                            EventId = "e4",
                            Category = "Exhibition",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Display of student artworks",
                            Location = "Art Gallery",
                            RSVPCount = 0,
                            Title = "Art Exhibition"
                        },
                        new
                        {
                            EventId = "e5",
                            Category = "Competition",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "24-hour coding competition",
                            Location = "Lab 2",
                            RSVPCount = 0,
                            Title = "Coding Hackathon"
                        },
                        new
                        {
                            EventId = "e6",
                            Category = "Concert",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Live student bands",
                            Location = "Auditorium",
                            RSVPCount = 0,
                            Title = "Music Concert"
                        },
                        new
                        {
                            EventId = "e7",
                            Category = "Theatre",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "School theatre production",
                            Location = "Main Stage",
                            RSVPCount = 0,
                            Title = "Drama Play"
                        },
                        new
                        {
                            EventId = "e8",
                            Category = "Workshop",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Build and program robots",
                            Location = "Engineering Lab",
                            RSVPCount = 0,
                            Title = "Robotics Workshop"
                        },
                        new
                        {
                            EventId = "e9",
                            Category = "Competition",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Capture campus life",
                            Location = "Online",
                            RSVPCount = 0,
                            Title = "Photography Contest"
                        },
                        new
                        {
                            EventId = "e10",
                            Category = "Sports",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Various sporting events",
                            Location = "Stadium",
                            RSVPCount = 0,
                            Title = "Sports Day"
                        },
                        new
                        {
                            EventId = "e11",
                            Category = "Fair",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meet potential employers",
                            Location = "Conference Hall",
                            RSVPCount = 0,
                            Title = "Career Fair"
                        },
                        new
                        {
                            EventId = "e12",
                            Category = "Competition",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test your chess skills",
                            Location = "Room 202",
                            RSVPCount = 0,
                            Title = "Chess Tournament"
                        },
                        new
                        {
                            EventId = "e13",
                            Category = "Seminar",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 27, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn about sustainability",
                            Location = "Lecture Hall 1",
                            RSVPCount = 0,
                            Title = "Environmental Seminar"
                        },
                        new
                        {
                            EventId = "e14",
                            Category = "Fair",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Find volunteering opportunities",
                            Location = "Lobby",
                            RSVPCount = 0,
                            Title = "Volunteer Fair"
                        },
                        new
                        {
                            EventId = "e15",
                            Category = "Workshop",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Practice foreign languages",
                            Location = "Room 303",
                            RSVPCount = 0,
                            Title = "Language Exchange"
                        },
                        new
                        {
                            EventId = "e16",
                            Category = "Workshop",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn new recipes",
                            Location = "Kitchen Lab",
                            RSVPCount = 0,
                            Title = "Cooking Class"
                        },
                        new
                        {
                            EventId = "e17",
                            Category = "Seminar",
                            CreatedBy = "u2",
                            Date = new DateTime(2025, 12, 31, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest trends in technology",
                            Location = "Lecture Hall 2",
                            RSVPCount = 0,
                            Title = "Tech Talk"
                        },
                        new
                        {
                            EventId = "e18",
                            Category = "Exhibition",
                            CreatedBy = "u2",
                            Date = new DateTime(2026, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Student short films",
                            Location = "Auditorium",
                            RSVPCount = 0,
                            Title = "Film Screening"
                        },
                        new
                        {
                            EventId = "e19",
                            Category = "Workshop",
                            CreatedBy = "u2",
                            Date = new DateTime(2026, 1, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn new dance routines",
                            Location = "Dance Studio",
                            RSVPCount = 0,
                            Title = "Dance Workshop"
                        },
                        new
                        {
                            EventId = "e20",
                            Category = "Party",
                            CreatedBy = "u2",
                            Date = new DateTime(2026, 1, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Celebrate the new year!",
                            Location = "Campus Center",
                            RSVPCount = 0,
                            Title = "New Year Party"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.RSVP", b =>
                {
                    b.Property<string>("RSVPId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RSVPId");

                    b.ToTable("RSVPs");

                    b.HasData(
                        new
                        {
                            RSVPId = "r1",
                            EventId = "e1",
                            Timestamp = new DateTime(2025, 12, 11, 2, 42, 36, 213, DateTimeKind.Local).AddTicks(340),
                            UserId = "u1"
                        },
                        new
                        {
                            RSVPId = "r2",
                            EventId = "e2",
                            Timestamp = new DateTime(2025, 12, 11, 2, 42, 36, 213, DateTimeKind.Local).AddTicks(345),
                            UserId = "u1"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "u1",
                            DisplayName = "John Student",
                            Email = "student@example.com",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = "u2",
                            DisplayName = "Jane Organizer",
                            Email = "organizer@example.com",
                            Role = "Organizer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
