// <auto-generated />
using System;
using CampusConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusConnect.Models.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LocationId");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = "event1",
                            Category = "Social",
                            CreatedById = "org1",
                            Date = new DateTime(2026, 3, 4, 3, 19, 36, 431, DateTimeKind.Utc).AddTicks(2239),
                            Description = "Welcome new students! Meet your peers and faculty.",
                            LocationId = "loc1",
                            Title = "Orientation Day"
                        },
                        new
                        {
                            EventId = "event2",
                            Category = "Educational",
                            CreatedById = "org1",
                            Date = new DateTime(2026, 3, 7, 3, 19, 36, 431, DateTimeKind.Utc).AddTicks(2247),
                            Description = "Learn to code in C# and build small projects.",
                            LocationId = "loc2",
                            Title = "Coding Workshop"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.Location", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = "loc1",
                            Description = "The large auditorium in the main building.",
                            Name = "Main Auditorium"
                        },
                        new
                        {
                            LocationId = "loc2",
                            Description = "Central hub for student activities.",
                            Name = "Student Center"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.RSVP", b =>
                {
                    b.Property<string>("RSVPId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RSVPId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("RSVPs", (string)null);

                    b.HasData(
                        new
                        {
                            RSVPId = "rsvp1",
                            EventId = "event1",
                            Timestamp = new DateTime(2026, 2, 25, 3, 19, 36, 431, DateTimeKind.Utc).AddTicks(2272),
                            UserId = "user1"
                        },
                        new
                        {
                            RSVPId = "rsvp2",
                            EventId = "event2",
                            Timestamp = new DateTime(2026, 2, 25, 3, 19, 36, 431, DateTimeKind.Utc).AddTicks(2274),
                            UserId = "user2"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user1",
                            DisplayName = "Alice",
                            Email = "alice@student.edu",
                            Password = "password1",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = "user2",
                            DisplayName = "Bob",
                            Email = "bob@student.edu",
                            Password = "password2",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = "org1",
                            DisplayName = "Prof. Smith",
                            Email = "smith@campus.edu",
                            Password = "password3",
                            Role = "Organizer"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.Event", b =>
                {
                    b.HasOne("CampusConnect.Models.User", "CreatedBy")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CampusConnect.Models.RSVP", b =>
                {
                    b.HasOne("CampusConnect.Models.Event", "Event")
                        .WithMany("RSVPs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", "User")
                        .WithMany("RSVPs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusConnect.Models.Event", b =>
                {
                    b.Navigation("RSVPs");
                });

            modelBuilder.Entity("CampusConnect.Models.Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Navigation("CreatedEvents");

                    b.Navigation("RSVPs");
                });
#pragma warning restore 612, 618
        }
    }
}
